apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: rpi4
      containers:
      - name: nginx
        image: saurabh221089/nginx_alpine:9dc6380
        # resources:
        #   requests:
        #     memory: "128Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "384Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
      #   volumeMounts:
      #   - name: web-content
      #     mountPath: /usr/share/nginx/html
      # volumes:
      # - name: web-content
      #   hostPath:
      #     path: /root/nginx_docker_container/profile/
      #     type: Directory
